"""
Entry and exit signal generation for the swing trading strategy.

Signals are generated by combining multiple technical indicators
(EMA alignment, RSI levels, volume spikes) into a single composite
score.  Each function returns a ``pandas.Series`` of signal values
aligned with the input DataFrame's index.

Dependencies: pandas, numpy
"""

from __future__ import annotations

from enum import IntEnum

import numpy as np
import pandas as pd

from config import (
    EMA_FAST,
    EMA_MEDIUM,
    EMA_SLOW,
    RSI_OVERSOLD,
    RSI_OVERBOUGHT,
    REWARD_RISK_RATIO,
)


class Signal(IntEnum):
    """Discrete signal labels used throughout the system."""

    SELL = -1
    HOLD = 0
    BUY = 1


# ──────────────────────────────────────────────
# Component checks
# ──────────────────────────────────────────────

def _ema_bullish_alignment(df: pd.DataFrame) -> pd.Series:
    """Check if EMAs are in bullish order: fast > medium > slow.

    Args:
        df: DataFrame with ``ema_20``, ``ema_50``, ``ema_200`` columns.

    Returns:
        Boolean Series — ``True`` where bullish EMA alignment holds.
    """
    return (
        (df[f"ema_{EMA_FAST}"] > df[f"ema_{EMA_MEDIUM}"])
        & (df[f"ema_{EMA_MEDIUM}"] > df[f"ema_{EMA_SLOW}"])
    )


def _ema_bearish_alignment(df: pd.DataFrame) -> pd.Series:
    """Check if EMAs are in bearish order: fast < medium < slow.

    Args:
        df: DataFrame with ``ema_20``, ``ema_50``, ``ema_200`` columns.

    Returns:
        Boolean Series — ``True`` where bearish EMA alignment holds.
    """
    return (
        (df[f"ema_{EMA_FAST}"] < df[f"ema_{EMA_MEDIUM}"])
        & (df[f"ema_{EMA_MEDIUM}"] < df[f"ema_{EMA_SLOW}"])
    )


def _rsi_oversold(df: pd.DataFrame) -> pd.Series:
    """Check if RSI is at or below the oversold threshold.

    Args:
        df: DataFrame with an ``rsi`` column.

    Returns:
        Boolean Series.
    """
    return df["rsi"] <= RSI_OVERSOLD


def _rsi_overbought(df: pd.DataFrame) -> pd.Series:
    """Check if RSI is at or above the overbought threshold.

    Args:
        df: DataFrame with an ``rsi`` column.

    Returns:
        Boolean Series.
    """
    return df["rsi"] >= RSI_OVERBOUGHT


def _price_above_ema(df: pd.DataFrame, ema_col: str) -> pd.Series:
    """Check if the close price is above a specific EMA.

    Args:
        df:      OHLCV + indicator DataFrame.
        ema_col: Name of the EMA column to compare against.

    Returns:
        Boolean Series.
    """
    return df["close"] > df[ema_col]


def _price_below_ema(df: pd.DataFrame, ema_col: str) -> pd.Series:
    """Check if the close price is below a specific EMA.

    Args:
        df:      OHLCV + indicator DataFrame.
        ema_col: Name of the EMA column to compare against.

    Returns:
        Boolean Series.
    """
    return df["close"] < df[ema_col]


# ──────────────────────────────────────────────
# Composite entry signal
# ──────────────────────────────────────────────

def generate_entry_signal(df: pd.DataFrame) -> pd.Series:
    """Produce a BUY / SELL / HOLD signal for each bar.

    **BUY** criteria (all must be true):
      1. Bullish EMA alignment (20 > 50 > 200).
      2. RSI ≤ oversold threshold (pullback into trend).
      3. Volume spike present (institutional participation).

    **SELL** criteria (all must be true):
      1. Bearish EMA alignment (20 < 50 < 200).
      2. RSI ≥ overbought threshold.
      3. Volume spike present.

    Args:
        df: OHLCV DataFrame already enriched with indicators
            (call ``indicators.add_all_indicators`` first).

    Returns:
        An integer ``pandas.Series`` of :class:`Signal` values.
    """
    buy_mask = (
        _ema_bullish_alignment(df)
        & _rsi_oversold(df)
        & df["volume_spike"]
    )

    sell_mask = (
        _ema_bearish_alignment(df)
        & _rsi_overbought(df)
        & df["volume_spike"]
    )

    signal = pd.Series(Signal.HOLD, index=df.index, name="entry_signal")
    signal[buy_mask] = Signal.BUY
    signal[sell_mask] = Signal.SELL
    return signal


# ──────────────────────────────────────────────
# Exit signal (trend exhaustion / reversal)
# ──────────────────────────────────────────────

def generate_exit_signal(
    df: pd.DataFrame,
    position_side: int = Signal.BUY,
) -> pd.Series:
    """Produce an exit flag for open positions.

    For a **long** position the exit triggers when:
      * RSI crosses above the overbought level, **or**
      * Price closes below the medium EMA.

    For a **short** position the exit triggers when:
      * RSI crosses below the oversold level, **or**
      * Price closes above the medium EMA.

    Args:
        df:            Enriched OHLCV DataFrame.
        position_side: ``Signal.BUY`` (long) or ``Signal.SELL`` (short).

    Returns:
        Boolean ``pandas.Series`` — ``True`` where an exit is warranted.
    """
    ema_med_col = f"ema_{EMA_MEDIUM}"

    if position_side == Signal.BUY:
        return (
            _rsi_overbought(df)
            | _price_below_ema(df, ema_med_col)
        ).rename("exit_signal")

    # short position
    return (
        _rsi_oversold(df)
        | _price_above_ema(df, ema_med_col)
    ).rename("exit_signal")


# ──────────────────────────────────────────────
# Pullback entry screener (single-bar verdict)
# ──────────────────────────────────────────────

def check_entry_signal(df: pd.DataFrame, nifty_df: pd.DataFrame | None = None) -> dict:
    """Evaluate the *latest bar* of an OHLCV DataFrame against a strict
    set of swing-trade entry conditions.

    The function computes all required indicators internally, so the
    caller may pass a **raw** OHLCV DataFrame (columns: ``open``,
    ``high``, ``low``, ``close``, ``volume``).

    **All ten conditions must be True for a BUY signal:**

    1. Close is above both EMA-50 and EMA-200 (uptrend).
    2. EMA-20 is above EMA-50 (short-term momentum).
    3. Price has pulled back 5-10 % from the rolling 10-day high.
    4. RSI (14) is between 45 and 58 (not overbought, not oversold).
    5. The last 3 candles show declining volume **and** today's volume
       is above its own 5-day average (volume dry-up then expansion).
    6. Today's candle is bullish (close > open).
    7. Relative Strength vs Nifty 50 over 20 days > 0
       (stock outperforming the benchmark).
    8. Price must have pulled back for at least 2 consecutive days
       (close < prev close for 2 days before today).
    9. ADX (14) > 20 (confirms a trending market, not sideways).
    10. (Reserved for future use.)

    Args:
        df:       OHLCV ``pandas.DataFrame`` with a DatetimeIndex.  Must
                  contain at least 200 rows for the slowest EMA to warm up.
        nifty_df: Optional OHLCV DataFrame for the Nifty 50 index
                  (``^NSEI``).  If ``None``, the relative-strength
                  check is skipped (treated as passed).

    Returns:
        A dict with two keys:

        * ``"signal"`` -- ``True`` if all conditions are met, else ``False``.
        * ``"reason"`` -- A human-readable string listing which conditions
          passed or failed.

    Example::

        >>> result = check_entry_signal(ohlcv_df, nifty_df)
        >>> if result["signal"]:
        ...     print("Entry triggered:", result["reason"])
    """
    from strategy.indicators import ema, rsi as compute_rsi, adx as compute_adx

    # -- Ensure we have enough data -----------
    if len(df) < 200:
        return {
            "signal": False,
            "reason": "Insufficient data: need >= 200 bars for EMA-200 warm-up.",
        }

    # -- Compute indicators on a copy ---------
    data = df.copy()
    data["ema_20"]  = ema(data["close"], 20)
    data["ema_50"]  = ema(data["close"], 50)
    data["ema_200"] = ema(data["close"], 200)
    data["rsi"]     = compute_rsi(data["close"], period=14)
    data["adx"]     = compute_adx(data["high"], data["low"], data["close"], period=14)

    # Latest bar values
    latest  = data.iloc[-1]
    close   = latest["close"]
    open_   = latest["open"]
    ema20   = latest["ema_20"]
    ema50   = latest["ema_50"]
    ema200  = latest["ema_200"]
    rsi_val = latest["rsi"]
    adx_val = latest["adx"]
    volume  = latest["volume"]

    reasons: list[str] = []

    # -- Condition 1: Close > EMA-50 AND Close > EMA-200 --
    cond1 = (close > ema50) and (close > ema200)
    reasons.append(
        f"{'[PASS]' if cond1 else '[FAIL]'} Close ({close:.2f}) "
        f"{'above' if cond1 else 'NOT above'} EMA-50 ({ema50:.2f}) "
        f"& EMA-200 ({ema200:.2f})"
    )

    # -- Condition 2: EMA-20 > EMA-50 --------
    cond2 = ema20 > ema50
    reasons.append(
        f"{'[PASS]' if cond2 else '[FAIL]'} EMA-20 ({ema20:.2f}) "
        f"{'above' if cond2 else 'NOT above'} EMA-50 ({ema50:.2f})"
    )

    # -- Condition 3: Pullback 5-10% from 10-day high --
    high_10d = data["high"].rolling(window=10).max().iloc[-1]
    pullback_pct = ((high_10d - close) / high_10d) * 100.0
    cond3 = 5.0 <= pullback_pct <= 10.0
    reasons.append(
        f"{'[PASS]' if cond3 else '[FAIL]'} Pullback {pullback_pct:.2f}% from "
        f"10-day high ({high_10d:.2f}) -- need 5-10%"
    )

    # -- Condition 4: RSI between 45 and 58 --
    cond4 = 45.0 <= rsi_val <= 58.0
    reasons.append(
        f"{'[PASS]' if cond4 else '[FAIL]'} RSI ({rsi_val:.2f}) "
        f"{'inside' if cond4 else 'outside'} 45-58 range"
    )

    # -- Condition 5: Last 3 candles declining volume + today > 5-day avg --
    vol_series = data["volume"]
    declining_vol = (
        vol_series.iloc[-4] > vol_series.iloc[-3]
        and vol_series.iloc[-3] > vol_series.iloc[-2]
    )
    vol_avg_5 = vol_series.iloc[-6:-1].mean()   # 5-day avg *before* today
    vol_expansion = volume > vol_avg_5
    cond5 = declining_vol and vol_expansion
    reasons.append(
        f"{'[PASS]' if declining_vol else '[FAIL]'} Last 3 candles declining volume | "
        f"{'[PASS]' if vol_expansion else '[FAIL]'} Today vol ({volume:,.0f}) "
        f"{'>' if vol_expansion else '<='} 5-day avg ({vol_avg_5:,.0f})"
    )

    # -- Condition 6: Bullish candle (close > open) --
    cond6 = close > open_
    reasons.append(
        f"{'[PASS]' if cond6 else '[FAIL]'} Bullish candle -- "
        f"Close ({close:.2f}) {'>' if cond6 else '<='} Open ({open_:.2f})"
    )

    # -- Condition 7: Relative Strength vs Nifty 50 --
    if nifty_df is not None and len(nifty_df) >= 20:
        stock_return_20d = (
            (data["close"].iloc[-1] - data["close"].iloc[-20])
            / data["close"].iloc[-20]
        ) * 100.0
        nifty_return_20d = (
            (nifty_df["close"].iloc[-1] - nifty_df["close"].iloc[-20])
            / nifty_df["close"].iloc[-20]
        ) * 100.0
        rs_score = stock_return_20d - nifty_return_20d
        cond7 = rs_score > 0
        reasons.append(
            f"{'[PASS]' if cond7 else '[FAIL]'} RS score ({rs_score:+.2f}%) "
            f"-- stock {stock_return_20d:+.2f}% vs Nifty {nifty_return_20d:+.2f}%"
        )
    else:
        cond7 = True  # skip if no benchmark data available
        reasons.append("[SKIP] RS vs Nifty -- no benchmark data provided")

    # -- Condition 8: 2 consecutive pullback days before today --
    cond8 = (
        data["close"].iloc[-2] < data["close"].iloc[-3]
        and data["close"].iloc[-3] < data["close"].iloc[-4]
    )
    reasons.append(
        f"{'[PASS]' if cond8 else '[FAIL]'} 2 consecutive pullback days "
        f"before entry candle"
    )

    # -- Condition 9: ADX(14) > 20 (trending) --
    cond9 = adx_val > 20.0
    reasons.append(
        f"{'[PASS]' if cond9 else '[FAIL]'} ADX ({adx_val:.2f}) "
        f"{'>' if cond9 else '<='} 20 -- {'trending' if cond9 else 'sideways'}"
    )

    # -- Composite verdict --------------------
    signal = all([cond1, cond2, cond3, cond4, cond5, cond6, cond7, cond8, cond9])
    summary = "ALL CONDITIONS MET - ENTRY" if signal else "Entry conditions NOT met"

    return {
        "signal": signal,
        "reason": f"{summary}\n" + "\n".join(reasons),
    }


# ──────────────────────────────────────────────
# Exit condition screener (single-bar verdict)
# ──────────────────────────────────────────────

def check_exit_signal(
    df: pd.DataFrame,
    entry_price: float,
    entry_date,
    stop_loss: float,
    target: float,
    max_hold_days: int = 7,
    partial_taken: bool = False,
) -> str:
    """Evaluate the latest bar and return an exit reason string.

    The function checks conditions in **priority order** and returns
    the first one that fires.  If nothing triggers, ``"HOLD"`` is
    returned.

    Priority order:

    1. ``"TARGET_HIT"``        -- close >= *target*.
    2. ``"STOP_LOSS"``         -- close <= *stop_loss*.
    3. ``"PARTIAL_EXIT_5PCT"`` -- profit >= 5 % and partial exit not
                                  yet taken (*partial_taken* is False).
    4. ``"TIME_EXIT"``         -- trading days since *entry_date*
                                  >= *max_hold_days* (default 7).
    5. ``"MOMENTUM_FADE"``     -- RSI (14) drops below 45 after entry
                                  (momentum has faded).
    6. ``"RSI_OVERBOUGHT"``    -- RSI (14) crosses above 70.
    7. ``"BEARISH_REVERSAL"``  -- a bearish engulfing candle forms
                                  near a local resistance level
                                  (20-bar rolling high).
    8. ``"HOLD"``              -- none of the above.

    Args:
        df:             OHLCV ``pandas.DataFrame`` with a DatetimeIndex.
        entry_price:    The price at which the position was opened.
        entry_date:     The date/timestamp the position was opened.
        stop_loss:      Absolute stop-loss price.
        target:         Absolute take-profit target price.
        max_hold_days:  Maximum number of **trading** (business) days
                        to hold the position (default ``7``).
        partial_taken:  Whether a partial exit (50 %) has already been
                        booked for this trade.  When ``False`` and
                        profit >= 5 %, returns ``"PARTIAL_EXIT_5PCT"``.

    Returns:
        One of the following literal strings:

        * ``"TARGET_HIT"``
        * ``"STOP_LOSS"``
        * ``"PARTIAL_EXIT_5PCT"``
        * ``"TIME_EXIT"``
        * ``"MOMENTUM_FADE"``
        * ``"RSI_OVERBOUGHT"``
        * ``"BEARISH_REVERSAL"``
        * ``"HOLD"``

    Raises:
        ValueError: If *df* has fewer than 2 rows.
    """
    from strategy.indicators import rsi as compute_rsi  # avoid circular import

    if len(df) < 2:
        raise ValueError(
            f"DataFrame must have >= 2 rows for exit checks, got {len(df)}"
        )

    latest = df.iloc[-1]
    prev   = df.iloc[-2]
    close  = latest["close"]

    # -- 1. TARGET_HIT ------------------------
    if close >= target:
        return "TARGET_HIT"

    # -- 2. STOP_LOSS -------------------------
    if close <= stop_loss:
        return "STOP_LOSS"

    # -- 3. PARTIAL_EXIT_5PCT -----------------
    current_pnl_pct = ((close - entry_price) / entry_price) * 100.0
    if not partial_taken and current_pnl_pct >= 5.0:
        return "PARTIAL_EXIT_5PCT"

    # -- 4. TIME_EXIT -------------------------
    entry_ts  = pd.Timestamp(entry_date)
    latest_ts = pd.Timestamp(df.index[-1])
    trading_days = len(pd.bdate_range(start=entry_ts, end=latest_ts)) - 1
    if trading_days >= max_hold_days:
        return "TIME_EXIT"

    # -- 5. MOMENTUM_FADE (RSI < 45) ---------
    rsi_series = compute_rsi(df["close"], period=14)
    rsi_now  = rsi_series.iloc[-1]
    rsi_prev = rsi_series.iloc[-2]
    if rsi_now < 45:
        return "MOMENTUM_FADE"

    # -- 6. RSI_OVERBOUGHT (cross above 70) --
    if rsi_now > 70 and rsi_prev <= 70:
        return "RSI_OVERBOUGHT"

    # -- 7. BEARISH_REVERSAL ------------------
    bearish_engulfing = (
        latest["open"] > prev["close"]
        and latest["close"] < prev["open"]
        and prev["close"] > prev["open"]   # previous was bullish
        and latest["close"] < latest["open"]  # today is bearish
    )
    if bearish_engulfing:
        resistance = df["high"].rolling(window=20).max().iloc[-1]
        near_resistance = (resistance - close) / resistance <= 0.01
        if near_resistance:
            return "BEARISH_REVERSAL"

    # -- 8. Nothing triggered -----------------
    return "HOLD"


# ──────────────────────────────────────────────
# Convenience: attach signals to DataFrame
# ──────────────────────────────────────────────

def add_signals(df: pd.DataFrame) -> pd.DataFrame:
    """Attach ``entry_signal`` and ``exit_long`` / ``exit_short`` columns.

    Args:
        df: OHLCV DataFrame already enriched with all indicators.

    Returns:
        DataFrame with three new signal columns.
    """
    df["entry_signal"] = generate_entry_signal(df)
    df["exit_long"] = generate_exit_signal(df, Signal.BUY)
    df["exit_short"] = generate_exit_signal(df, Signal.SELL)
    return df
