"""
Entry and exit signal generation for the swing trading strategy.

Signals are generated by combining multiple technical indicators
(EMA alignment, RSI levels, volume spikes) into a single composite
score.  Each function returns a ``pandas.Series`` of signal values
aligned with the input DataFrame's index.

Dependencies: pandas, numpy
"""

from __future__ import annotations

from enum import IntEnum

import numpy as np
import pandas as pd

from config import (
    EMA_FAST,
    EMA_MEDIUM,
    EMA_SLOW,
    RSI_OVERSOLD,
    RSI_OVERBOUGHT,
    REWARD_RISK_RATIO,
)


class Signal(IntEnum):
    """Discrete signal labels used throughout the system."""

    SELL = -1
    HOLD = 0
    BUY = 1


# ──────────────────────────────────────────────
# Component checks
# ──────────────────────────────────────────────

def _ema_bullish_alignment(df: pd.DataFrame) -> pd.Series:
    """Check if EMAs are in bullish order: fast > medium > slow.

    Args:
        df: DataFrame with ``ema_20``, ``ema_50``, ``ema_200`` columns.

    Returns:
        Boolean Series — ``True`` where bullish EMA alignment holds.
    """
    return (
        (df[f"ema_{EMA_FAST}"] > df[f"ema_{EMA_MEDIUM}"])
        & (df[f"ema_{EMA_MEDIUM}"] > df[f"ema_{EMA_SLOW}"])
    )


def _ema_bearish_alignment(df: pd.DataFrame) -> pd.Series:
    """Check if EMAs are in bearish order: fast < medium < slow.

    Args:
        df: DataFrame with ``ema_20``, ``ema_50``, ``ema_200`` columns.

    Returns:
        Boolean Series — ``True`` where bearish EMA alignment holds.
    """
    return (
        (df[f"ema_{EMA_FAST}"] < df[f"ema_{EMA_MEDIUM}"])
        & (df[f"ema_{EMA_MEDIUM}"] < df[f"ema_{EMA_SLOW}"])
    )


def _rsi_oversold(df: pd.DataFrame) -> pd.Series:
    """Check if RSI is at or below the oversold threshold.

    Args:
        df: DataFrame with an ``rsi`` column.

    Returns:
        Boolean Series.
    """
    return df["rsi"] <= RSI_OVERSOLD


def _rsi_overbought(df: pd.DataFrame) -> pd.Series:
    """Check if RSI is at or above the overbought threshold.

    Args:
        df: DataFrame with an ``rsi`` column.

    Returns:
        Boolean Series.
    """
    return df["rsi"] >= RSI_OVERBOUGHT


def _price_above_ema(df: pd.DataFrame, ema_col: str) -> pd.Series:
    """Check if the close price is above a specific EMA.

    Args:
        df:      OHLCV + indicator DataFrame.
        ema_col: Name of the EMA column to compare against.

    Returns:
        Boolean Series.
    """
    return df["close"] > df[ema_col]


def _price_below_ema(df: pd.DataFrame, ema_col: str) -> pd.Series:
    """Check if the close price is below a specific EMA.

    Args:
        df:      OHLCV + indicator DataFrame.
        ema_col: Name of the EMA column to compare against.

    Returns:
        Boolean Series.
    """
    return df["close"] < df[ema_col]


# ──────────────────────────────────────────────
# Composite entry signal
# ──────────────────────────────────────────────

def generate_entry_signal(df: pd.DataFrame) -> pd.Series:
    """Produce a BUY / SELL / HOLD signal for each bar.

    **BUY** criteria (all must be true):
      1. Bullish EMA alignment (20 > 50 > 200).
      2. RSI ≤ oversold threshold (pullback into trend).
      3. Volume spike present (institutional participation).

    **SELL** criteria (all must be true):
      1. Bearish EMA alignment (20 < 50 < 200).
      2. RSI ≥ overbought threshold.
      3. Volume spike present.

    Args:
        df: OHLCV DataFrame already enriched with indicators
            (call ``indicators.add_all_indicators`` first).

    Returns:
        An integer ``pandas.Series`` of :class:`Signal` values.
    """
    buy_mask = (
        _ema_bullish_alignment(df)
        & _rsi_oversold(df)
        & df["volume_spike"]
    )

    sell_mask = (
        _ema_bearish_alignment(df)
        & _rsi_overbought(df)
        & df["volume_spike"]
    )

    signal = pd.Series(Signal.HOLD, index=df.index, name="entry_signal")
    signal[buy_mask] = Signal.BUY
    signal[sell_mask] = Signal.SELL
    return signal


# ──────────────────────────────────────────────
# Exit signal (trend exhaustion / reversal)
# ──────────────────────────────────────────────

def generate_exit_signal(
    df: pd.DataFrame,
    position_side: int = Signal.BUY,
) -> pd.Series:
    """Produce an exit flag for open positions.

    For a **long** position the exit triggers when:
      * RSI crosses above the overbought level, **or**
      * Price closes below the medium EMA.

    For a **short** position the exit triggers when:
      * RSI crosses below the oversold level, **or**
      * Price closes above the medium EMA.

    Args:
        df:            Enriched OHLCV DataFrame.
        position_side: ``Signal.BUY`` (long) or ``Signal.SELL`` (short).

    Returns:
        Boolean ``pandas.Series`` — ``True`` where an exit is warranted.
    """
    ema_med_col = f"ema_{EMA_MEDIUM}"

    if position_side == Signal.BUY:
        return (
            _rsi_overbought(df)
            | _price_below_ema(df, ema_med_col)
        ).rename("exit_signal")

    # short position
    return (
        _rsi_oversold(df)
        | _price_above_ema(df, ema_med_col)
    ).rename("exit_signal")


# ──────────────────────────────────────────────
# Pullback entry screener (single-bar verdict)
# ──────────────────────────────────────────────

def check_entry_signal(df: pd.DataFrame) -> dict:
    """Evaluate the *latest bar* of an OHLCV DataFrame against a strict
    set of swing-trade entry conditions.

    The function computes all required indicators internally, so the
    caller may pass a **raw** OHLCV DataFrame (columns: ``open``,
    ``high``, ``low``, ``close``, ``volume``).

    **All six conditions must be True for a BUY signal:**

    1. Close is above both EMA-50 and EMA-200 (uptrend).
    2. EMA-20 is above EMA-50 (short-term momentum).
    3. Price has pulled back 5–10 % from the rolling 10-day high.
    4. RSI (14) is between 40 and 55 (not overbought, not oversold).
    5. The last 3 candles show declining volume **and** today's volume
       is above its own 5-day average (volume dry-up then expansion).
    6. Today's candle is bullish (close > open).

    Args:
        df: OHLCV ``pandas.DataFrame`` with a DatetimeIndex.  Must
            contain at least 200 rows for the slowest EMA to warm up.

    Returns:
        A dict with two keys:

        * ``"signal"`` — ``True`` if all conditions are met, else ``False``.
        * ``"reason"`` — A human-readable string listing which conditions
          passed (✓) and which failed (✗).

    Example::

        >>> result = check_entry_signal(ohlcv_df)
        >>> if result["signal"]:
        ...     print("Entry triggered:", result["reason"])
    """
    from strategy.indicators import ema, rsi as compute_rsi  # local import to avoid circular ref

    # ── Ensure we have enough data ───────────
    if len(df) < 200:
        return {
            "signal": False,
            "reason": "Insufficient data: need ≥ 200 bars for EMA-200 warm-up.",
        }

    # ── Compute indicators on a copy ─────────
    data = df.copy()
    data["ema_20"]  = ema(data["close"], 20)
    data["ema_50"]  = ema(data["close"], 50)
    data["ema_200"] = ema(data["close"], 200)
    data["rsi"]     = compute_rsi(data["close"], period=14)

    # Latest bar values
    latest  = data.iloc[-1]
    close   = latest["close"]
    open_   = latest["open"]
    ema20   = latest["ema_20"]
    ema50   = latest["ema_50"]
    ema200  = latest["ema_200"]
    rsi_val = latest["rsi"]
    volume  = latest["volume"]

    reasons: list[str] = []

    # ── Condition 1: Close > EMA-50 AND Close > EMA-200 ──
    cond1 = (close > ema50) and (close > ema200)
    reasons.append(
        f"{'✓' if cond1 else '✗'} Close ({close:.2f}) "
        f"{'above' if cond1 else 'NOT above'} EMA-50 ({ema50:.2f}) "
        f"& EMA-200 ({ema200:.2f})"
    )

    # ── Condition 2: EMA-20 > EMA-50 ────────
    cond2 = ema20 > ema50
    reasons.append(
        f"{'✓' if cond2 else '✗'} EMA-20 ({ema20:.2f}) "
        f"{'above' if cond2 else 'NOT above'} EMA-50 ({ema50:.2f})"
    )

    # ── Condition 3: Pullback 5–10 % from 10-day high ──
    high_10d = data["high"].rolling(window=10).max().iloc[-1]
    pullback_pct = ((high_10d - close) / high_10d) * 100.0
    cond3 = 5.0 <= pullback_pct <= 10.0
    reasons.append(
        f"{'✓' if cond3 else '✗'} Pullback {pullback_pct:.2f}% from "
        f"10-day high ({high_10d:.2f}) — need 5–10%"
    )

    # ── Condition 4: RSI between 40 and 55 ──
    cond4 = 40.0 <= rsi_val <= 55.0
    reasons.append(
        f"{'✓' if cond4 else '✗'} RSI ({rsi_val:.2f}) "
        f"{'inside' if cond4 else 'outside'} 40–55 range"
    )

    # ── Condition 5: Last 3 candles declining volume + today > 5-day avg ──
    vol_series = data["volume"]
    declining_vol = (
        vol_series.iloc[-4] > vol_series.iloc[-3]
        and vol_series.iloc[-3] > vol_series.iloc[-2]
    )
    vol_avg_5 = vol_series.iloc[-6:-1].mean()   # 5-day avg *before* today
    vol_expansion = volume > vol_avg_5
    cond5 = declining_vol and vol_expansion
    reasons.append(
        f"{'✓' if declining_vol else '✗'} Last 3 candles declining volume | "
        f"{'✓' if vol_expansion else '✗'} Today vol ({volume:,.0f}) "
        f"{'>' if vol_expansion else '≤'} 5-day avg ({vol_avg_5:,.0f})"
    )

    # ── Condition 6: Bullish candle (close > open) ──
    cond6 = close > open_
    reasons.append(
        f"{'✓' if cond6 else '✗'} Bullish candle — "
        f"Close ({close:.2f}) {'>' if cond6 else '≤'} Open ({open_:.2f})"
    )

    # ── Composite verdict ────────────────────
    signal = all([cond1, cond2, cond3, cond4, cond5, cond6])
    summary = "ALL CONDITIONS MET ✅" if signal else "Entry conditions NOT met ❌"

    return {
        "signal": signal,
        "reason": f"{summary}\n" + "\n".join(reasons),
    }


# ──────────────────────────────────────────────
# Exit condition screener (single-bar verdict)
# ──────────────────────────────────────────────

def check_exit_signal(
    df: pd.DataFrame,
    entry_price: float,
    entry_date,
    stop_loss: float,
    target: float,
    max_hold_days: int = 10,
) -> str:
    """Evaluate the latest bar and return an exit reason string.

    The function checks conditions in **priority order** and returns
    the first one that fires.  If nothing triggers, ``"HOLD"`` is
    returned.

    Priority order:

    1. ``"TARGET_HIT"``        – close ≥ *target*.
    2. ``"STOP_LOSS"``         – close ≤ *stop_loss*.
    3. ``"TIME_EXIT"``         – trading days since *entry_date*
                                  ≥ *max_hold_days*.
    4. ``"RSI_OVERBOUGHT"``    – RSI (14) crosses above 70.
    5. ``"BEARISH_REVERSAL"``  – a bearish engulfing candle forms
                                  near a local resistance level
                                  (20-bar rolling high).
    6. ``"HOLD"``              – none of the above.

    The function computes EMA-20/50/200, RSI-14, and the bearish-
    engulfing pattern internally, so it accepts a **raw** OHLCV
    DataFrame.

    Args:
        df:             OHLCV ``pandas.DataFrame`` with a DatetimeIndex.
                        Must contain columns: ``open``, ``high``,
                        ``low``, ``close``, ``volume``.
        entry_price:    The price at which the position was opened.
        entry_date:     The date/timestamp the position was opened.
                        Anything accepted by ``pd.Timestamp()``.
        stop_loss:      Absolute stop-loss price.
        target:         Absolute take-profit target price.
        max_hold_days:  Maximum number of **trading** (business) days
                        to hold the position before a time-based exit
                        (default ``10``).

    Returns:
        One of the following literal strings:

        * ``"TARGET_HIT"``
        * ``"STOP_LOSS"``
        * ``"TIME_EXIT"``
        * ``"RSI_OVERBOUGHT"``
        * ``"BEARISH_REVERSAL"``
        * ``"HOLD"``

    Raises:
        ValueError: If *df* has fewer than 2 rows (need previous bar
                    for engulfing check and RSI cross detection).

    Example::

        >>> reason = check_exit_signal(
        ...     ohlcv_df,
        ...     entry_price=1020.0,
        ...     entry_date="2024-03-01",
        ...     stop_loss=989.40,
        ...     target=1101.60,
        ... )
        >>> if reason != "HOLD":
        ...     execute_exit(reason)
    """
    from strategy.indicators import rsi as compute_rsi  # avoid circular import

    if len(df) < 2:
        raise ValueError(
            f"DataFrame must have ≥ 2 rows for exit checks, got {len(df)}"
        )

    latest = df.iloc[-1]
    prev   = df.iloc[-2]
    close  = latest["close"]

    # ── 1. TARGET_HIT ────────────────────────
    if close >= target:
        return "TARGET_HIT"

    # ── 2. STOP_LOSS ─────────────────────────
    if close <= stop_loss:
        return "STOP_LOSS"

    # ── 3. TIME_EXIT ─────────────────────────
    entry_ts  = pd.Timestamp(entry_date)
    latest_ts = pd.Timestamp(df.index[-1])
    # Count only trading (business) days between entry and now
    trading_days = len(pd.bdate_range(start=entry_ts, end=latest_ts)) - 1
    if trading_days >= max_hold_days:
        return "TIME_EXIT"

    # ── 4. RSI_OVERBOUGHT (cross above 70) ──
    rsi_series = compute_rsi(df["close"], period=14)
    rsi_now  = rsi_series.iloc[-1]
    rsi_prev = rsi_series.iloc[-2]
    if rsi_now > 70 and rsi_prev <= 70:
        return "RSI_OVERBOUGHT"

    # ── 5. BEARISH_REVERSAL ──────────────────
    #    Bearish engulfing: today's open > prev close AND
    #    today's close < prev open  (red candle fully engulfs
    #    previous green body).
    #    "At resistance" = close is within 1 % of the 20-bar
    #    rolling high.
    bearish_engulfing = (
        latest["open"] > prev["close"]
        and latest["close"] < prev["open"]
        and prev["close"] > prev["open"]   # previous was bullish
        and latest["close"] < latest["open"]  # today is bearish
    )
    if bearish_engulfing:
        resistance = df["high"].rolling(window=20).max().iloc[-1]
        near_resistance = (resistance - close) / resistance <= 0.01
        if near_resistance:
            return "BEARISH_REVERSAL"

    # ── 6. Nothing triggered ─────────────────
    return "HOLD"


# ──────────────────────────────────────────────
# Convenience: attach signals to DataFrame
# ──────────────────────────────────────────────

def add_signals(df: pd.DataFrame) -> pd.DataFrame:
    """Attach ``entry_signal`` and ``exit_long`` / ``exit_short`` columns.

    Args:
        df: OHLCV DataFrame already enriched with all indicators.

    Returns:
        DataFrame with three new signal columns.
    """
    df["entry_signal"] = generate_entry_signal(df)
    df["exit_long"] = generate_exit_signal(df, Signal.BUY)
    df["exit_short"] = generate_exit_signal(df, Signal.SELL)
    return df
